name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Install v
        run: cd && git clone --depth=1 https://github.com/vlang/v && cd v && make && ./v symlink

      - name: Build
        run: v .
