name: Go Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install v
        run: cd && git clone --depth=1 https://github.com/vlang/v && cd v && make && ./v symlink

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install 3.12

      - name: Run linter
        shell: bash
        run: uv venv && source .venv/bin/activate && uv pip install pre-commit && pre-commit run -a
