name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Install v
        run: cd && git clone --depth=1 https://github.com/vlang/v && cd v && make && ./v symlink

      - name: Build
        run: v .

      - name: Create GitHub Pre-Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }} - VivaDB Pre-Release
          artifacts: "vivadb*"
          generateReleaseNotes: true
          draft: false
          prerelease: true
