name: GitHub Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: vivadb-linux
            binary_extension: ""
          - os: macos-latest
            artifact_name: vivadb-macos
            binary_extension: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install V (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          cd $HOME
          git clone --depth=1 https://github.com/vlang/v
          cd v
          make
          ./v symlink

      - name: Build binary
        run: v -prod -o ${{ matrix.artifact_name }}${{ matrix.binary_extension }} .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}${{ matrix.binary_extension }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./artifacts/*/*"
          generateReleaseNotes: true
          draft: false
          prerelease: false
